const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { readDb, writeDb } = require('./lib/supabase-repository');

const PORT = Number(process.env.PORT || 4173);
const ROOT = __dirname;
const PUBLIC_DIR = path.join(ROOT, 'public');
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'Athifayangbuat';
const ADMIN_SESSION_SECRET = process.env.ADMIN_SESSION_SECRET || ADMIN_PASSWORD;
function resolveAssignment(db, employeeId, date) {
  return db.assignments?.filter(a => a.employeeId === employeeId && a.effectiveFrom <= date && (!a.effectiveTo || a.effectiveTo >= date)).sort((a,b) => b.effectiveFrom.localeCompare(a.effectiveFrom))[0];
}
function makassarToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function eachDate(from,to){const dates=[];for(let day=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);day<=end;day.setUTCDate(day.getUTCDate()+1))dates.push(day.toISOString().slice(0,10));return dates;}
function effectiveEntries(db){
  const exclusions=new Set(db.entries.filter(e=>e.status!=='VOID'&&e.entryKind==='AUTO_EXCLUSION').map(e=>`${e.date}|${e.employeeId}|${e.ruleId}`));
  const legacyOffRuleIds=new Set(db.rules.filter(r=>/^OFF (AO|KASIR|TERAPIS)$/i.test(r.description)).map(r=>r.id));
  const daysOff=new Set([
    ...(db.daysOff||[]).filter(e=>e.status!=='VOID').map(e=>`${e.date}|${e.employeeId}`),
    ...db.entries.filter(e=>e.status!=='VOID'&&legacyOffRuleIds.has(e.ruleId)).map(e=>`${e.date}|${e.employeeId}`),
  ]);
  const manual=db.entries.filter(e=>e.entryKind!=='AUTO_EXCLUSION'&&!legacyOffRuleIds.has(e.ruleId)&&!db.rules.find(r=>r.id===e.ruleId)?.autoDaily);
  const today=makassarToday();
  const employeeStarts=new Map();
  for(const entry of db.entries.filter(e=>e.status!=='VOID')){
    const current=employeeStarts.get(entry.employeeId);
    if(!current||entry.date<current)employeeStarts.set(entry.employeeId,entry.date);
  }
  const starts=[...employeeStarts.values()].sort();
  if(!starts.length)return manual;
  const automatic=[];
  for(const date of eachDate(starts[0],today))for(const employee of db.employees.filter(e=>e.status==='ACTIVE'&&e.position!=='KAPTEN')){
    if(!employeeStarts.has(employee.id)||date<employeeStarts.get(employee.id))continue;
    const assignment=resolveAssignment(db,employee.id,date);if(daysOff.has(`${date}|${employee.id}`))continue;
    for(const rule of db.rules.filter(r=>r.status==='ACTIVE'&&r.autoDaily&&(!r.roles.length||r.roles.includes(employee.position)))){
      if(exclusions.has(`${date}|${employee.id}|${rule.id}`))continue;
      automatic.push({id:`auto-${date}-${employee.id}-${rule.id}`,employeeId:employee.id,ruleId:rule.id,outletId:assignment?.outletId||null,date,quantity:1,multiplier:1,basePoints:rule.points,totalPoints:rule.points,notes:'Poin harian otomatis',entryKind:'AUTO',status:'CONFIRMED',createdAt:`${date}T00:00:00+08:00`,updatedAt:`${date}T00:00:00+08:00`});
    }
  }
  const derived=[],derivedStartMonth=String(db.meta?.automaticPointsEnabledAt||today).slice(0,7),confirmed=db.entries.filter(e=>e.status!=='VOID'&&e.entryKind!=='AUTO_EXCLUSION'),lateIds=new Set(db.rules.filter(r=>/^Lambat /i.test(r.description)).map(r=>r.id));
  const confirmedRulesByEmployeeDate=new Map(),confirmedByEmployeeMonth=new Map();
  for(const entry of confirmed){
    const dayKey=`${entry.employeeId}|${entry.date}`,monthKey=`${entry.employeeId}|${entry.date.slice(0,7)}`;
    if(!confirmedRulesByEmployeeDate.has(dayKey))confirmedRulesByEmployeeDate.set(dayKey,new Set());
    confirmedRulesByEmployeeDate.get(dayKey).add(entry.ruleId);
    if(!confirmedByEmployeeMonth.has(monthKey))confirmedByEmployeeMonth.set(monthKey,[]);
    confirmedByEmployeeMonth.get(monthKey).push(entry);
  }
  const hasAnyRule=(employeeId,date,ruleIds)=>{
    const present=confirmedRulesByEmployeeDate.get(`${employeeId}|${date}`);if(!present)return false;
    for(const ruleId of ruleIds)if(present.has(ruleId))return true;return false;
  };
  for(const month of [...new Set(eachDate(starts[0],today).map(d=>d.slice(0,7)))])for(const employee of db.employees.filter(e=>e.status==='ACTIVE'&&e.position!=='KAPTEN')){
    if(month<derivedStartMonth)continue;
    const monthStart=`${month}-01`,monthEnd=new Date(Date.UTC(+month.slice(0,4),+month.slice(5,7),0)).toISOString().slice(0,10),periodEnd=monthEnd<today?monthEnd:today,employeeStart=employeeStarts.get(employee.id),onTime=db.rules.find(r=>r.autoDaily&&r.description==='Datang tepat waktu'&&r.roles.includes(employee.position));
    if(!employeeStart||employeeStart>periodEnd)continue;
    const qualifies=dates=>onTime&&dates.every(date=>date>=employeeStart&&!daysOff.has(`${date}|${employee.id}`)&&!exclusions.has(`${date}|${employee.id}|${onTime.id}`)&&!hasAnyRule(employee.id,date,lateIds));
    const add=(rule,date,note)=>derived.push({id:`derived-${rule.id}-${date}-${employee.id}`,employeeId:employee.id,ruleId:rule.id,outletId:resolveAssignment(db,employee.id,date)?.outletId||null,date,quantity:1,multiplier:1,basePoints:rule.points,totalPoints:rule.points,notes:note,entryKind:'DERIVED',status:'CONFIRMED'});
    const weekly=db.rules.find(r=>r.status==='ACTIVE'&&r.derivedType==='WEEKLY_ATTENDANCE'&&r.roles.includes(employee.position));if(weekly)for(let day=1;day<=28;day+=7){const from=`${month}-${String(day).padStart(2,'0')}`,to=`${month}-${String(day+6).padStart(2,'0')}`;if(to<=periodEnd&&qualifies(eachDate(from,to)))add(weekly,to,'Poin mingguan otomatis');}
    const monthly=db.rules.find(r=>r.status==='ACTIVE'&&r.derivedType==='MONTHLY_ATTENDANCE'&&r.roles.includes(employee.position));if(monthly&&monthEnd<=today&&qualifies(eachDate(monthStart,monthEnd)))add(monthly,monthEnd,'Poin bulanan otomatis');
    const monthEntries=confirmedByEmployeeMonth.get(`${employee.id}|${month}`)||[];
    if(employee.position==='TERAPIS'){const guests=monthEntries.filter(e=>e.date<=periodEnd).reduce((sum,e)=>{const match=db.rules.find(r=>r.id===e.ruleId)?.description.match(/^([2-5]) tamu seharian$/i);return sum+(match?+match[1]*(e.quantity||1):0);},0);for(const type of guests>=50?['MONTHLY_GUEST_45','MONTHLY_GUEST_50']:guests>=45?['MONTHLY_GUEST_45']:[]){const rule=db.rules.find(r=>r.status==='ACTIVE'&&r.derivedType===type);if(rule)add(rule,periodEnd,`Total ${guests} tamu bulan ini`);}}
    for(const rule of db.rules.filter(r=>r.status==='ACTIVE'&&r.automation?.type==='NO_OCCURRENCE'&&!r.derivedType&&(!r.roles.length||r.roles.includes(employee.position)))){
      const blockers=new Set(rule.automation.blockerRuleIds||[]),valid=dates=>dates.every(date=>date>=employeeStart&&(!rule.automation.blockOnDayOff||!daysOff.has(`${date}|${employee.id}`))&&(!rule.automation.requiredDailyRuleId||!exclusions.has(`${date}|${employee.id}|${rule.automation.requiredDailyRuleId}`))&&!hasAnyRule(employee.id,date,blockers));
      if(rule.automation.period==='MONTHLY'&&monthEnd<=today&&valid(eachDate(monthStart,monthEnd)))add(rule,monthEnd,'Poin kondisi bulanan otomatis');
      if(rule.automation.period==='WEEKLY')for(let day=1;day<=28;day+=7){const from=`${month}-${String(day).padStart(2,'0')}`,to=`${month}-${String(day+6).padStart(2,'0')}`;if(to<=periodEnd&&valid(eachDate(from,to)))add(rule,to,'Poin kondisi mingguan otomatis');}
    }
    for(const rule of db.rules.filter(r=>r.status==='ACTIVE'&&r.automation?.type==='ACCUMULATION'&&!r.derivedType&&(!r.roles.length||r.roles.includes(employee.position)))){const total=monthEntries.filter(e=>e.date<=periodEnd&&(rule.automation.sourceRuleIds||[]).includes(e.ruleId)).reduce((sum,e)=>sum+(e.quantity||1),0);if(total>=Number(rule.automation.threshold||0))add(rule,periodEnd,`Akumulasi ${total}`);}
  }
  return [...manual,...automatic,...derived].sort((a,b)=>`${b.date}${b.createdAt||''}`.localeCompare(`${a.date}${a.createdAt||''}`));
}
const json = (res,status,value) => { res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value)); };
const uid = () => crypto.randomUUID(); const clean = value => String(value||'').trim();
function verifyPassword(value){const submitted=Buffer.from(String(value||'')),expected=Buffer.from(ADMIN_PASSWORD);return submitted.length===expected.length&&crypto.timingSafeEqual(submitted,expected);}
function createAdminToken(){const payload=Buffer.from(JSON.stringify({exp:Date.now()+8*60*60*1000,nonce:crypto.randomBytes(12).toString('hex')})).toString('base64url'),signature=crypto.createHmac('sha256',ADMIN_SESSION_SECRET).update(payload).digest('base64url');return `${payload}.${signature}`;}
function verifyAdminToken(token){try{const [payload,signature]=String(token||'').split('.');if(!payload||!signature)return false;const expected=crypto.createHmac('sha256',ADMIN_SESSION_SECRET).update(payload).digest('base64url'),a=Buffer.from(signature),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return false;return JSON.parse(Buffer.from(payload,'base64url').toString()).exp>Date.now();}catch{return false;}}
function requireAdmin(req,res){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!verifyAdminToken(token)){json(res,403,{error:'Admin authentication required.'});return false;}return true;}
function requestBody(req){return new Promise((resolve,reject)=>{let value='';req.on('data',c=>{value+=c;if(value.length>1_000_000)reject(new Error('Payload too large'));});req.on('end',()=>{try{resolve(value?JSON.parse(value):{});}catch(e){reject(e);}});});}
function enrich(db,entry){const employee=db.employees.find(x=>x.id===entry.employeeId),rule=db.rules.find(x=>x.id===entry.ruleId),outlet=db.outlets.find(x=>x.id===entry.outletId);return{...entry,employee:employee?{...employee,role:employee.position,active:employee.status==='ACTIVE',outlet:outlet?.name?.toUpperCase()}:null,rule:rule?{...rule,supportsMultiplier:rule.isMultipliable,active:rule.status==='ACTIVE'}:null,outlet};}
function audit(db,action,entityType,entityId,before=null,after=null){db.audit.unshift({id:uid(),action,entityType,entityId,actor:'Admin',before,after,at:new Date().toISOString()});}
function validateEmployee(p){const name=clean(p.name),position=clean(p.position).toUpperCase(),gender=clean(p.gender).toUpperCase(),city=clean(p.city).toUpperCase(),status=clean(p.status).toUpperCase();if(!name)return{error:'Employee name is required.'};if(!['KASIR','AO','TERAPIS','KAPTEN'].includes(position))return{error:'Please select a valid position.'};if(!['PRIA','WANITA'].includes(gender))return{error:'Please select a valid gender.'};if(city&&!['PALU','MAKASSAR'].includes(city))return{error:'Please select a valid city.'};if(!['ACTIVE','INACTIVE'].includes(status))return{error:'Please select a valid status.'};return{value:{name,position,role:position,gender,city:city?city[0]+city.slice(1).toLowerCase():'',status,active:status==='ACTIVE'}};}
function validateRule(p){const description=clean(p.description),category=clean(p.category).toUpperCase(),points=Number(p.points);if(!description)return{error:'Point type name is required.'};if(!['PENGURANGAN','PENAMBAHAN','PRESTASI'].includes(category))return{error:'Please select a valid category.'};if(!Number.isFinite(points))return{error:'Base points must be a number.'};const roles=Array.isArray(p.roles)?p.roles.filter(x=>['KASIR','AO','TERAPIS'].includes(x)):[];const status=clean(p.status||'ACTIVE').toUpperCase(),type=clean(p.automationType||p.automation?.type||'MANUAL').toUpperCase();const automation=type==='MANUAL'?null:{type,period:clean(p.automationPeriod||p.automation?.period||'MONTHLY').toUpperCase(),blockerRuleIds:Array.isArray(p.blockerRuleIds)?p.blockerRuleIds:[],sourceRuleIds:Array.isArray(p.sourceRuleIds)?p.sourceRuleIds:[],requiredDailyRuleId:clean(p.requiredDailyRuleId||''),targetRuleId:clean(p.targetRuleId||p.automation?.targetRuleId||''),blockOnDayOff:Boolean(p.blockOnDayOff),threshold:Number(p.threshold||0)};return{value:{description,category,points,isMultipliable:Boolean(p.isMultipliable),supportsMultiplier:Boolean(p.isMultipliable),autoDaily:type==='DAILY_DEFAULT',automation,frequency:clean(p.frequency||'EVENT').toUpperCase(),roles,status,active:status==='ACTIVE'}};}
function validateEntry(db,p){const employee=db.employees.find(x=>x.id===p.employeeId&&x.status==='ACTIVE'),rule=db.rules.find(x=>x.id===p.ruleId&&x.status==='ACTIVE');if(!employee)return{error:'Please select an active employee.'};if(employee.position==='KAPTEN')return{error:'Kapten tidak memiliki poin.'};if(!rule)return{error:'Please select an active point type.'};if(!/^\d{4}-\d{2}-\d{2}$/.test(p.date||''))return{error:'Please provide a valid date.'};if(rule.roles.length&&!rule.roles.includes(employee.position))return{error:`${employee.name} is not eligible for this point type.`};const quantity=rule.isMultipliable?Number(p.quantity||p.multiplier||1):1;if(!Number.isFinite(quantity)||quantity<1)return{error:'Quantity must be at least 1.'};const assignment=resolveAssignment(db,employee.id,p.date);return{value:{employeeId:employee.id,ruleId:rule.id,outletId:assignment?.outletId||null,date:p.date,quantity,multiplier:quantity,basePoints:rule.points,totalPoints:Number((rule.points*quantity).toFixed(2)),notes:clean(p.notes).slice(0,500)}};}
function serveFile(res,pathname){const requested=pathname==='/'?'index.html':pathname.replace(/^\//,''),resolved=path.resolve(PUBLIC_DIR,requested);if(!resolved.startsWith(path.resolve(PUBLIC_DIR))||!fs.existsSync(resolved)||fs.statSync(resolved).isDirectory()){res.writeHead(404);return res.end('Not found');}const type={'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml'}[path.extname(resolved)]||'application/octet-stream';res.writeHead(200,{'Content-Type':`${type}; charset=utf-8`});fs.createReadStream(resolved).pipe(res);}

const handler=async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{
  if(url.pathname==='/api/auth/admin'&&req.method==='POST'){const p=await requestBody(req);if(!verifyPassword(p.password))return json(res,401,{error:'Password Admin salah. Anda tetap dalam mode Viewer.'});return json(res,200,{token:createAdminToken(),role:'ADMIN',expiresIn:28800});}
  if(url.pathname==='/api/bootstrap'&&req.method==='GET'){const db=await readDb(),requestedMonth=/^\d{4}-\d{2}$/.test(url.searchParams.get('month')||'')?url.searchParams.get('month'):makassarToday().slice(0,7),requestedYear=/^\d{4}$/.test(url.searchParams.get('year')||'')?url.searchParams.get('year'):requestedMonth.slice(0,4),effective=effectiveEntries(db),annualMap=new Map();for(const entry of effective.filter(e=>e.status!=='VOID'&&e.date.startsWith(`${requestedYear}-`))){const key=`${entry.employeeId}|${entry.date.slice(0,7)}`;annualMap.set(key,(annualMap.get(key)||0)+Number(entry.totalPoints||0));}const availableYears=[...new Set([...db.entries.map(e=>e.date?.slice(0,4)),makassarToday().slice(0,4)].filter(year=>/^\d{4}$/.test(year)))].sort((a,b)=>b.localeCompare(a));return json(res,200,{employees:db.employees,outlets:db.outlets,assignments:db.assignments,rules:db.rules,entries:effective.filter(e=>e.date.startsWith(requestedMonth)).map(e=>enrich(db,e)),annualScores:[...annualMap].map(([key,total])=>{const [employeeId,month]=key.split('|');return{employeeId,month,total};}),availableYears,autoExclusions:db.entries.filter(e=>e.status!=='VOID'&&e.entryKind==='AUTO_EXCLUSION'&&e.date.startsWith(requestedMonth)).map(e=>enrich(db,e)),daysOff:db.daysOff.filter(e=>e.status!=='VOID'&&e.date.startsWith(requestedMonth)).map(e=>({...e,employee:db.employees.find(x=>x.id===e.employeeId)})),audit:db.audit.slice(0,50)});}
  if(url.pathname==='/api/days-off'&&req.method==='POST'){if(!requireAdmin(req,res))return;const db=await readDb(),p=await requestBody(req),employee=db.employees.find(e=>e.id===p.employeeId&&e.status==='ACTIVE');if(!employee||employee.position==='KAPTEN')return json(res,400,{error:'Pilih karyawan aktif.'});if(!/^\d{4}-\d{2}-\d{2}$/.test(p.date||''))return json(res,400,{error:'Tanggal tidak valid.'});if(db.daysOff.some(e=>e.status!=='VOID'&&e.employeeId===p.employeeId&&e.date===p.date))return json(res,409,{error:'Karyawan sudah ditandai OFF pada tanggal ini.'});const item={id:uid(),employeeId:p.employeeId,date:p.date,status:'CONFIRMED',createdAt:new Date().toISOString()};db.daysOff.unshift(item);audit(db,'CREATE','DAY_OFF',item.id,null,item);await writeDb(db);return json(res,201,item);}
  const dm=url.pathname.match(/^\/api\/days-off\/([^/]+)$/);if(dm&&req.method==='DELETE'){if(!requireAdmin(req,res))return;const db=await readDb(),item=db.daysOff.find(e=>e.id===dm[1]);if(!item)return json(res,404,{error:'Data OFF tidak ditemukan.'});item.status='VOID';audit(db,'VOID','DAY_OFF',item.id,null,item);await writeDb(db);return json(res,200,{ok:true});}
  if(url.pathname==='/api/employees'&&req.method==='POST'){if(!requireAdmin(req,res))return;const db=await readDb(),p=await requestBody(req),checked=validateEmployee(p);if(checked.error)return json(res,400,{error:checked.error});if(db.employees.some(e=>e.name.toLowerCase()===checked.value.name.toLowerCase()))return json(res,409,{error:'An employee with this name already exists.'});const employee={id:uid(),...checked.value,createdAt:new Date().toISOString()};db.employees.push(employee);if(p.outletId&&db.outlets.some(o=>o.id===p.outletId))db.assignments.push({id:uid(),employeeId:employee.id,outletId:p.outletId,captainGroup:['A','B'].includes(p.captainGroup)?p.captainGroup:'A',effectiveFrom:p.effectiveFrom||new Date().toISOString().slice(0,7)+'-01',effectiveTo:null,assignedBy:'admin'});audit(db,'CREATE','EMPLOYEE',employee.id,null,employee);await writeDb(db);return json(res,201,employee);}
  const em=url.pathname.match(/^\/api\/employees\/([^/]+)$/);if(em&&req.method==='PUT'){if(!requireAdmin(req,res))return;const db=await readDb(),i=db.employees.findIndex(e=>e.id===em[1]);if(i<0)return json(res,404,{error:'Employee not found.'});const p=await requestBody(req),checked=validateEmployee(p);if(checked.error)return json(res,400,{error:checked.error});const before={...db.employees[i]};db.employees[i]={...db.employees[i],...checked.value,updatedAt:new Date().toISOString()};audit(db,'UPDATE','EMPLOYEE',em[1],before,db.employees[i]);await writeDb(db);return json(res,200,db.employees[i]);}
  if(url.pathname==='/api/assignments'&&req.method==='POST'){if(!requireAdmin(req,res))return;const db=await readDb(),p=await requestBody(req);if(!/^\d{4}-\d{2}$/.test(p.month||''))return json(res,400,{error:'A valid rotation month is required.'});if(!Array.isArray(p.assignments))return json(res,400,{error:'Assignments are required.'});const from=`${p.month}-01`;for(const item of p.assignments){if(!db.employees.some(e=>e.id===item.employeeId))continue;db.assignments.forEach(a=>{if(a.employeeId===item.employeeId&&a.effectiveFrom<=from&&(!a.effectiveTo||a.effectiveTo>=from)){if(a.effectiveFrom<from)a.effectiveTo=new Date(new Date(`${from}T00:00:00`).getTime()-86400000).toISOString().slice(0,10);else a._remove=true;}});if(db.outlets.some(o=>o.id===item.outletId))db.assignments.push({id:uid(),employeeId:item.employeeId,outletId:item.outletId,captainGroup:['A','B'].includes(item.captainGroup)?item.captainGroup:'A',effectiveFrom:from,effectiveTo:null,assignedBy:'admin'});}db.assignments=db.assignments.filter(a=>!a._remove);audit(db,'ROTATE','OUTLET_ASSIGNMENT',p.month,null,p.assignments);await writeDb(db);return json(res,200,{ok:true});}
  if(url.pathname==='/api/outlets'&&req.method==='POST'){if(!requireAdmin(req,res))return;const db=await readDb(),p=await requestBody(req),name=clean(p.name),city=clean(p.city);if(!name)return json(res,400,{error:'Nama outlet wajib diisi.'});if(!['Palu','Makassar'].includes(city))return json(res,400,{error:'Kota outlet wajib dipilih.'});if(db.outlets.some(o=>o.name.toLowerCase()===name.toLowerCase()&&o.status==='ACTIVE'))return json(res,409,{error:'Nama outlet sudah digunakan.'});const outlet={id:uid(),code:name.toUpperCase().replace(/[^A-Z0-9]+/g,'_'),name,city,color:clean(p.color)||'#d8d2ff',order:db.outlets.length+1,status:'ACTIVE'};db.outlets.push(outlet);audit(db,'CREATE','OUTLET',outlet.id,null,outlet);await writeDb(db);return json(res,201,outlet);}
  const om=url.pathname.match(/^\/api\/outlets\/([^/]+)$/);if(om&&req.method==='PUT'){if(!requireAdmin(req,res))return;const db=await readDb(),i=db.outlets.findIndex(o=>o.id===om[1]);if(i<0)return json(res,404,{error:'Outlet tidak ditemukan.'});const p=await requestBody(req),before={...db.outlets[i]},name=clean(p.name),city=clean(p.city);if(!name)return json(res,400,{error:'Nama outlet wajib diisi.'});if(!['Palu','Makassar'].includes(city))return json(res,400,{error:'Kota outlet wajib dipilih.'});db.outlets[i]={...db.outlets[i],name,city,color:clean(p.color)||db.outlets[i].color,status:clean(p.status||db.outlets[i].status)};audit(db,'UPDATE','OUTLET',om[1],before,db.outlets[i]);await writeDb(db);return json(res,200,db.outlets[i]);}if(om&&req.method==='DELETE'){if(!requireAdmin(req,res))return;const db=await readDb(),outlet=db.outlets.find(o=>o.id===om[1]);if(!outlet)return json(res,404,{error:'Outlet tidak ditemukan.'});const before={...outlet};outlet.status='INACTIVE';audit(db,'DEACTIVATE','OUTLET',outlet.id,before,outlet);await writeDb(db);return json(res,200,{ok:true});}
  if(url.pathname==='/api/rules'&&req.method==='POST'){if(!requireAdmin(req,res))return;const db=await readDb(),p=await requestBody(req),checked=validateRule(p);if(checked.error)return json(res,400,{error:checked.error});const rule={id:uid(),...checked.value,createdAt:new Date().toISOString()};db.rules.push(rule);audit(db,'CREATE','POINT_TYPE',rule.id,null,rule);await writeDb(db);return json(res,201,rule);}
  const rm=url.pathname.match(/^\/api\/rules\/([^/]+)$/);if(rm&&req.method==='PUT'){if(!requireAdmin(req,res))return;const db=await readDb(),i=db.rules.findIndex(r=>r.id===rm[1]);if(i<0)return json(res,404,{error:'Point type not found.'});const p=await requestBody(req),checked=validateRule(p);if(checked.error)return json(res,400,{error:checked.error});const before={...db.rules[i]};db.rules[i]={...db.rules[i],...checked.value,updatedAt:new Date().toISOString()};audit(db,'UPDATE','POINT_TYPE',rm[1],before,db.rules[i]);await writeDb(db);return json(res,200,db.rules[i]);}
  if(url.pathname==='/api/entry-batches'&&req.method==='POST'){if(!requireAdmin(req,res))return;const db=await readDb(),p=await requestBody(req);if(!Array.isArray(p.items)||!p.items.length)return json(res,400,{error:'Select at least one employee.'});const batchId=uid(),now=new Date().toISOString(),created=[],rule=db.rules.find(r=>r.id===p.ruleId);for(const item of p.items){const checked=validateEntry(db,{...item,date:p.date,ruleId:p.ruleId,notes:p.notes});if(checked.error)return json(res,400,{error:checked.error});if(rule?.automation?.type==='CANCEL_RULE'){const target=db.entries.find(e=>e.status!=='VOID'&&e.date===p.date&&e.employeeId===item.employeeId&&e.ruleId===rule.automation.targetRuleId);if(!target)return json(res,409,{error:'Poin target tidak ditemukan pada karyawan dan tanggal tersebut.'});target.status='VOID';target.updatedAt=now;created.push({id:uid(),batchId,...checked.value,totalPoints:0,entryKind:'CANCELLATION',cancelledEntryId:target.id,status:'CONFIRMED',createdAt:now,updatedAt:now});continue;}const duplicate=db.entries.find(e=>e.status!=='VOID'&&e.date===p.date&&e.employeeId===item.employeeId&&e.ruleId===p.ruleId&&(rule?.autoDaily?e.entryKind==='AUTO_EXCLUSION':e.entryKind!=='AUTO_EXCLUSION'));if(duplicate)return json(res,409,{error:rule?.autoDaily?'Poin otomatis karyawan tersebut sudah dihapus pada tanggal ini.':`${db.employees.find(e=>e.id===item.employeeId)?.name} already has this point on the selected date.`});created.push({id:uid(),batchId,...checked.value,totalPoints:rule?.autoDaily?0:checked.value.totalPoints,entryKind:rule?.autoDaily?'AUTO_EXCLUSION':'MANUAL',status:'CONFIRMED',createdAt:now,updatedAt:now});}db.batches.unshift({id:batchId,ruleId:p.ruleId,date:p.date,notes:clean(p.notes),createdBy:'Admin',createdAt:now});db.entries.unshift(...created);audit(db,rule?.automation?.type==='CANCEL_RULE'?'CANCEL_RULE':rule?.autoDaily?'CREATE_AUTO_EXCLUSION':'CREATE_BATCH','POINT_ENTRY',batchId,null,{count:created.length});await writeDb(db);return json(res,201,{batchId,action:rule?.automation?.type==='CANCEL_RULE'?'CANCELLED':rule?.autoDaily?'REMOVED':'ADDED',entries:created.map(e=>enrich(db,e))});}
  const xm=url.pathname.match(/^\/api\/entries\/([^/]+)$/);if(xm&&req.method==='PUT'){if(!requireAdmin(req,res))return;const db=await readDb(),i=db.entries.findIndex(e=>e.id===xm[1]);if(i<0)return json(res,404,{error:'Entry not found.'});const p=await requestBody(req),checked=validateEntry(db,p);if(checked.error)return json(res,400,{error:checked.error});const before={...db.entries[i]};db.entries[i]={...db.entries[i],...checked.value,updatedAt:new Date().toISOString()};audit(db,'UPDATE','POINT_ENTRY',xm[1],before,db.entries[i]);await writeDb(db);return json(res,200,enrich(db,db.entries[i]));}if(xm&&req.method==='DELETE'){if(!requireAdmin(req,res))return;const db=await readDb(),entry=db.entries.find(e=>e.id===xm[1]);if(!entry)return json(res,404,{error:'Entry not found.'});const before={...entry};entry.status='VOID';entry.updatedAt=new Date().toISOString();audit(db,'VOID','POINT_ENTRY',entry.id,before,entry);await writeDb(db);return json(res,200,{ok:true});}
  if(url.pathname.startsWith('/api/'))return json(res,404,{error:'Endpoint not found.'});serveFile(res,url.pathname);
}catch(error){console.error(error);json(res,500,{error:'Unexpected server error.'});}};

if(require.main===module){http.createServer(handler).listen(PORT,()=>console.log(`Poin Breaktime running at http://localhost:${PORT}`));}
module.exports={handler};
